name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  geolocator: ^13.0.3
  intl: ^0.20.2
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/wkaie.png"
  adaptive_icon_foreground: "assets/wkaieFG.png"
  adaptive_icon_background: "assets/wkaieBG.png"

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true